[book]
authors = ["HSGamer"]
language = "en"
multilingual = false
src = "src"
title = "EduBlock"

[output.html]
git-repository-url = "https://github.com/etases/EduBlock.Book"
git-repository-icon = "fa-github"
site-url = "/EduBlock.Book/"

[output.pdf]
static_site_url = "https://github.com/etases/EduBlock.Book"