name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt update
          sudo apt install libssl-dev pkg-config

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - name: Install mdbook
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook
          version: "^0.4"
          args: "--no-default-features"
          features: "search"

      - name: Install mdbook-pdf
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-pdf

      - name: Install mdbook-plantuml
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-plantuml
          args: "--no-default-features"
          features: "plantuml-ssl-server"

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html

      - uses: actions/upload-artifact@v3
        with:
          name: Book PDF
          path: book/pdf/output.pdf
